ShoppingCartORT/ShoppingCartORT/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using ShoppingCartORT.Data;

namespace ShoppingCartORT.Models
{
    public class Pedido
    {
        public int pedidoID { get; set; }
        public string nombre { get; set; }
        public Usuario usuario { get; set; }
        public List<Item> items { get; set; }

     
    
        public double ObtenerTotalPedido()
        {
            double SumaTotalPedido = 0;
            double ValorItem = 0;


            foreach (Item item in items)
            {
                ValorItem = item.ObtenerTotal();
                SumaTotalPedido = SumaTotalPedido + ValorItem;
            }

            return SumaTotalPedido;
        }



    }




}

ShoppingCartORT/ShoppingCartORT/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using ShoppingCartORT.Data;
using ShoppingCartORT.Models;
using Microsoft.AspNetCore.Http;

namespace ShoppingCartORT.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ShoppingCartORTContext _context;

        public PedidoController(ShoppingCartORTContext context)
        {
            _context = context;
        }


        // prueba pedidos

       public void VerPedidos()
       {
           var Pedidos = _context.Pedidos.Include("items.producto").Include("usuario")
                        .ToList();

            foreach (Pedido p in Pedidos)
            {

                Console.WriteLine(p.nombre);
                Console.WriteLine(p.usuario.nombre);
                Console.WriteLine(p.ObtenerTotalPedido());
                Console.WriteLine("detalle items");
                foreach (Item item in p.items)
                {
                    Console.WriteLine(item.producto.nombre);
                    Console.WriteLine(item.cantidad);
                    Console.WriteLine(item.ObtenerTotal());
                }
                    

            }


        }

        // GET: Pedido
        public async Task<IActionResult> Index()
        {
            var Pedidos = _context.Pedidos
                .Include("items.producto")
                .Include("usuario")
                .ToList();
            return View(Pedidos);
        }



        // GET: Pedido/Details/5
        public async Task<IActionResult> Details(int id)
        {
            Console.WriteLine("me llego el id" + id);
            var Pedido = _context.Pedidos
                .Where(p => p.pedidoID == id)
                .Include("items.producto")
                .Include("usuario")
                .FirstOrDefault();
            return View(Pedido);
        }


        // GET: Pedido/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pedido/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]        
        public JsonResult Create([FromBody] List<ItemDTO> items)
        {
            var userMail = HttpContext.Session.GetString("user");
            var usuarioFromDB = _context.Usuarios.ToList().Find(u => u.mail == userMail);

            //Creamos el pedido
            var pedido = new Pedido
            {
                nombre = "Nombre del pedido",
                usuario = usuarioFromDB
            };

            _context.Pedidos.Add(pedido);

            _context.SaveChanges();

            int id = pedido.pedidoID;

            foreach (ItemDTO item in items) {
                var productoFromDB = _context.Productos.ToList().Find(p => p.productoID == item.productoID);
                Item i = new Item();
                i.cantidad = item.cantidad;
                i.producto = productoFromDB;
                i.pedido = pedido;
                _context.Items.Add(i);
            }

            _context.SaveChanges();

            Console.WriteLine("******** "+ items);

            return Json(items.Count);
        }


        // GET: Pedido/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("pedidoID,nombre")] Pedido pedido)
        {
            if (id != pedido.pedidoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.pedidoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Pedido/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.pedidoID == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Pedidos.FindAsync(id);
            _context.Pedidos.Remove(pedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedidos.Any(e => e.pedidoID == id);
        }
    }
}

ShoppingCartORT/ShoppingCartORT/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ShoppingCartORT.Data;
using ShoppingCartORT.Models;
using Microsoft.AspNetCore.Http;

namespace ShoppingCartORT.Controllers
{
    public class ProductoController : Controller
    {
        private readonly ShoppingCartORTContext _context;

        public ProductoController(ShoppingCartORTContext context)
        {
            _context = context;
        }

        // GET: Producto
        public async Task<IActionResult> Index()
        {
            var userLogueado = HttpContext.Session.GetString("user");
            if (userLogueado == null || userLogueado == "") {
                return RedirectToAction("Login", "Usuario");
            }
            return View(await _context.Productos.ToListAsync());
        }

        // GET: Producto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .FirstOrDefaultAsync(m => m.productoID == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // GET: Producto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Producto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("productoID,nombre,descripcion,precio")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(producto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos.FindAsync(id);
            if (producto == null)
            {
                return NotFound();
            }
            return View(producto);
        }

        // POST: Producto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("productoID,nombre,descripcion,precio")] Producto producto)
        {
            if (id != producto.productoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(producto);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductoExists(producto.productoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        // GET: Producto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producto = await _context.Productos
                .FirstOrDefaultAsync(m => m.productoID == id);
            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producto = await _context.Productos.FindAsync(id);
            _context.Productos.Remove(producto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductoExists(int id)
        {
            return _context.Productos.Any(e => e.productoID == id);
        }
    }
}

ShoppingCartORT/ShoppingCartORT/Views/Pedido/Create.cshtml
@model ShoppingCartORT.Models.Pedido

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <title>Create</title>
</head>
<body>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

ShoppingCartORT/ShoppingCartORT/Views/Pedido/Delete.cshtml
@model ShoppingCartORT.Models.Pedido

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="pedidoID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

ShoppingCartORT/ShoppingCartORT/Views/Pedido/Details.cshtml
@model ShoppingCartORT.Models.Pedido

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

    <table class="table table-striped" style=" border: solid #d6d2d2 0.5px; box-shadow: 5px 10px 8px #888888;">
        <thead class="table-primary">
            <tr>
                <th>
                    Nombre producto
                </th>
                <th>
                    Precio Unitario
                </th>
                <th>
                    Cantidad
                </th>
                <th>
                    Total
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (var Item in Model.items)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => Item.producto.nombre)
                    </td>
                    <td>
                        $@Html.DisplayFor(x => Item.producto.precio)
                    </td>
                    <td>
                        @Html.DisplayFor(x => Item.cantidad)

                    </td>
                    <td>
                        @{var total = Item.ObtenerTotal();
                        }
                        $@Html.DisplayFor(x => total)
                    </td>

                    <td>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <button type="button" class="btn btn-secondary" style=" float: right;">
        <a asp-area="" asp-controller="Pedido" asp-action="Index" style="color: white !important;text-decoration: none;">Volver</a>
    </button>

ShoppingCartORT/ShoppingCartORT/Views/Pedido/Edit.cshtml
@model ShoppingCartORT.Models.Pedido

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Pedido</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="pedidoID" />
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

ShoppingCartORT/ShoppingCartORT/Views/Pedido/Index.cshtml
@model IEnumerable<ShoppingCartORT.Models.Pedido>

@{
    
    Layout = "~/Views/Shared/_Layout.cshtml";
    double totalGeneral = 0;
}

<!DOCTYPE html>

    <table class="table table-striped" style=" border: solid #d6d2d2 0.5px; box-shadow: 5px 10px 8px #888888;">
        <thead class="table-primary">
            <tr>
                <th>
                    #
                </th>
                <th>
                    Nombre Comprador
                </th>
                <th>
                    Total Pedido
                </th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pedido in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => pedido.pedidoID)
                    </td>
                    <td>
                        @Html.DisplayFor(x => pedido.usuario.nombre)

                    </td>
                    <td>
                        @{
                            var total = pedido.ObtenerTotalPedido();
                            totalGeneral = totalGeneral + total;
                        }
                        $@Html.DisplayFor(x => total)
                    </td>

                    <td>
                        <button type="button" class="btn btn-info">
                            <a asp-action="Details" asp-route-id="@pedido.pedidoID" style="color: white !important;text-decoration: none;">Detalle</a>
                        </button>
                    </td>
                </tr>
            }
            <tr class="table-success">
                <td>
                </td>
                <td>

                    <strong>GANANCIA TOTAL</strong>
                </td>
                <td>
                    @{
                        <strong>$ @Html.DisplayFor(x => totalGeneral)</strong>
                    }
                </td>
                <td>
                </td>
            </tr>
        </tbody>
    </table>
    <button type="button" class="btn btn-secondary" style=" float: right;">
        <a asp-controller="Producto" asp-action="Index" style="color: white !important;text-decoration: none;">Volver</a>
    </button>
