ShoppingCartORT/ShoppingCartORT/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using ShoppingCartORT.Data;
using ShoppingCartORT.Models;
using Microsoft.AspNetCore.Http;

namespace ShoppingCartORT.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ShoppingCartORTContext _context;

        public PedidoController(ShoppingCartORTContext context)
        {
            _context = context;
        }


        // prueba pedidos

       public void VerPedidos()
       {
           var Pedidos = _context.Pedidos.Include("items.producto").Include("usuario")
                        .ToList();

            foreach (Pedido p in Pedidos)
            {

                Console.WriteLine(p.nombre);
                Console.WriteLine(p.usuario.nombre);
                Console.WriteLine(p.ObtenerTotalPedido());
                Console.WriteLine("detalle items");
                foreach (Item item in p.items)
                {
                    Console.WriteLine(item.producto.nombre);
                    Console.WriteLine(item.cantidad);
                    Console.WriteLine(item.ObtenerTotal());
                }
                    

            }


        }

        // GET: Pedido
        public async Task<IActionResult> Index()
        {
            var Pedidos = _context.Pedidos
                .Include("items.producto")
                .Include("usuario")
                .ToList();
            return View(Pedidos);
        }



        // GET: Pedido/Details/5
        public async Task<IActionResult> Details(int id)
        {
            Console.WriteLine("me llego el id" + id);
            var Pedido = _context.Pedidos
                .Where(p => p.pedidoID == id)
                .Include("items.producto")
                .Include("usuario")
                .FirstOrDefault();
            return View(Pedido);
        }


        // GET: Pedido/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pedido/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]        
        public JsonResult Create([FromBody] List<ItemDTO> items)
        {
            var userMail = HttpContext.Session.GetString("user");
            var usuarioFromDB = _context.Usuarios.ToList().Find(u => u.mail == userMail);

            //Creamos el pedido
            var pedido = new Pedido
            {
                nombre = "Nombre del pedido",
                usuario = usuarioFromDB
            };

            _context.Pedidos.Add(pedido);

            _context.SaveChanges();

            int id = pedido.pedidoID;

            foreach (ItemDTO item in items) {
                var productoFromDB = _context.Productos.ToList().Find(p => p.productoID == item.productoID);
                Item i = new Item();
                i.cantidad = item.cantidad;
                i.producto = productoFromDB;
                i.pedido = pedido;
                _context.Items.Add(i);
            }

            _context.SaveChanges();

            Console.WriteLine("******** "+ items);

            return Json(items.Count);
        }


        // GET: Pedido/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos.FindAsync(id);
            if (pedido == null)
            {
                return NotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("pedidoID,nombre")] Pedido pedido)
        {
            if (id != pedido.pedidoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pedido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PedidoExists(pedido.pedidoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pedido);
        }

        // GET: Pedido/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pedido = await _context.Pedidos
                .FirstOrDefaultAsync(m => m.pedidoID == id);
            if (pedido == null)
            {
                return NotFound();
            }

            return View(pedido);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pedido = await _context.Pedidos.FindAsync(id);
            _context.Pedidos.Remove(pedido);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PedidoExists(int id)
        {
            return _context.Pedidos.Any(e => e.pedidoID == id);
        }
    }
}

ShoppingCartORT/ShoppingCartORT/Controllers/UsuarioController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShoppingCartORT.Data;
using ShoppingCartORT.Models;
using Microsoft.AspNetCore.Http;

namespace ShoppingCartORT.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly ShoppingCartORTContext _context;


        public UsuarioController(ShoppingCartORTContext context)
        {
            _context = context;            
        }

        // GET: Usuario
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios.ToListAsync());
        }

        // GET: Usuario/Login/
        public IActionResult Login()
        {
            return View();
        }

        // GET: Usuario/Logout/
        public RedirectToActionResult Logout()
        {
            HttpContext.Session.SetString("rol", string.Empty);
            HttpContext.Session.SetString("user", string.Empty);
            return RedirectToAction("Index", "Home");
            
        }

        // GET: Usuario/Login
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        public async Task<IActionResult> Login(String mail, String password)
        {
            if (ModelState.IsValid)
            {
                var usuarioFromDB = await _context.Usuarios.FirstOrDefaultAsync(usu => usu.mail == mail && usu.password == password);
                if (usuarioFromDB == null) {
                    ViewBag.Error = "Usuario o clave incorrectos.";
                    return View();
                }
                HttpContext.Session.SetString("user", usuarioFromDB.mail);
                HttpContext.Session.SetString("userNombre", usuarioFromDB.nombre);
                HttpContext.Session.SetString("userApellido", usuarioFromDB.apellido);
                HttpContext.Session.SetString("rol", usuarioFromDB.rol);
                return RedirectToAction("Index", "Producto");
            }
            return View(null);
        }



        // GET: Usuario/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.usuarioID == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuario/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuario/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("usuarioID,nombre,apellido,dni,password,mail")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                usuario.rol = "USER";
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View(usuario);
        }

        // GET: Usuario/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuario/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("usuarioID,nombre,apellido,dni,password,mail")] Usuario usuario)
        {
            if (id != usuario.usuarioID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.usuarioID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuario/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.usuarioID == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuario/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            _context.Usuarios.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.usuarioID == id);
        }
    }
}

ShoppingCartORT/ShoppingCartORT/Views/Shared/_Layout.cshtml

@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ShoppingCartORT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ShoppingCartORT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Producto" asp-action="Index">Productos</a>
                        </li>
                        @{
                            if (@HttpContextAccessor.HttpContext.Session.GetString("rol") == "ADMIN")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-light" asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a>
                                </li>
                             }
                        }
                        </ul>
                </div>
                @{
                    
                    if (@HttpContextAccessor.HttpContext.Session.GetString("user") == "" ||
                        @HttpContextAccessor.HttpContext.Session.GetString("user") == null)
                    {
                        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">
                            <a asp-area="" asp-controller="Usuario" asp-action="Create" style="color: white !important;text-decoration: none;">Registrarse </a>
                        </button>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="margin-left: 10px;">
                            <a asp-area="" asp-controller="Usuario" asp-action="Login" style="color: white !important;text-decoration: none;">Ingresar</a>
                        </button>
                    } else {
                        <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">
                            <a asp-area="" asp-controller="Usuario" asp-action="Logout" style="color: white !important;text-decoration: none;">Logout </a>
                        </button>
                    }
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ShoppingCartORT
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>